import type { Metadata } from 'next';
import { Geist, Geist_Mono, DM_Sans } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import { Toaster } from 'sonner';
import { ApiProvider } from './utils/ApiContext';

const dmSans = DM_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                'h-full dark',
                'antialiased',
                geistSans.variable,
                geistMono.variable,
                'font-sans',
                dmSans.variable,
            )}
        >
            <body className="h-full bg-slate-950 text-purple-100">
                <ApiProvider>
                    <SidebarProvider>
                        <AppSidebar />
                        <main className="w-full flex-1 overflow-auto bg-slate-950 md:w-screen md:h-screen">
                            <SidebarTrigger className="absolute m-2 hover:bg-slate-700 z-10" />
                            {children}
                        </main>
                    </SidebarProvider>
                    <Toaster />
                </ApiProvider>
            </body>
        </html>
    );
}
